# Workflow file for building and deploying a Python app to Azure Web App - AudioToTextPipeline
# Docs: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - AudioToTextPipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up the Python version for the environment
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies from the requirements.txt file
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Zip the contents of the application while excluding unnecessary files
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x ".git/*" -x ".github/*" -x "venv/*" -x "*.pyc" -x "__pycache__/*"

      # Upload the zipped artifact for the deployment job
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Login to Azure using credentials stored in GitHub Secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy to the Azure Web App using the downloaded and unzipped artifact
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'AudioToTextPipline'
          slot-name: 'Production'
        timeout-minutes: 60

      # Optional: Show directory structure for debugging purposes
      - name: Show directory structure (for debugging)
        run: ls -R
